version: '3'
services:
  mysql:
    image: "mysql:latest"
    container_name: "mysql9"
    environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    restart: always