// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package inject

import (
	"github.com/Jasonbourne723/socrates/app/controllers"
	"github.com/Jasonbourne723/socrates/app/services"
)

// Injectors from wire.go:

func InitializeAuthApi() controllers.AuthApi {
	iUserService := services.NewUserService()
	authApi := controllers.NewAuthApi(iUserService)
	return authApi
}
